// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydjmdlfwxqkvprjzqlik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkam1kbGZ3eHFrdnByanpxbGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzIwMDksImV4cCI6MjA2NDEwODAwOX0.RE--nv1e94MlOD4Nka_SOlfLCuqGJ3a_QwHSsaW8jFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);